
export interface Achievement {
  name: string;
  tier: 'Bronze' | 'Silver' | 'Gold' | 'Platinum' | 'Diamond' | 'Mythic';
  requirement: string;
  count: number;
  xp: number;
  icon: string;
  color: string;
  animation?: string;
}

export const BADGES: Achievement[] = [
  // 🥉 BRONZE (20)
  { name: "First Bite", tier: "Bronze", requirement: "Scan your first food item.", count: 1, xp: 10, icon: "fa-utensils", color: "from-orange-400 to-orange-600" },
  { name: "Double Bite", tier: "Bronze", requirement: "Scan 2 food items.", count: 2, xp: 10, icon: "fa-cookie", color: "from-orange-400 to-orange-600" },
  { name: "Hat-Trick", tier: "Bronze", requirement: "Scan 3 food items.", count: 3, xp: 10, icon: "fa-bowl-food", color: "from-orange-400 to-orange-600" },
  { name: "Welcome Aboard", tier: "Bronze", requirement: "Complete guest sign-in.", count: 0, xp: 10, icon: "fa-door-open", color: "from-orange-400 to-orange-600" },
  { name: "Healthy Start", tier: "Bronze", requirement: "Daily intake < 2000 kcal.", count: 1, xp: 10, icon: "fa-check", color: "from-orange-400 to-orange-600" },
  { name: "Protein Punch", tier: "Bronze", requirement: "Log > 30g protein meal.", count: 1, xp: 10, icon: "fa-egg", color: "from-orange-400 to-orange-600" },
  { name: "Carb Smart", tier: "Bronze", requirement: "Scan a low carb meal.", count: 1, xp: 10, icon: "fa-leaf", color: "from-orange-400 to-orange-600" },
  { name: "Fat Finder", tier: "Bronze", requirement: "Scan a high fat meal.", count: 1, xp: 10, icon: "fa-cheese", color: "from-orange-400 to-orange-600" },
  { name: "Green Plate", tier: "Bronze", requirement: "Scan a vegetable.", count: 1, xp: 10, icon: "fa-carrot", color: "from-orange-400 to-orange-600" },
  { name: "Fruit Lover", tier: "Bronze", requirement: "Scan a fruit.", count: 1, xp: 10, icon: "fa-apple-whole", color: "from-orange-400 to-orange-600" },
  { name: "Hydrated", tier: "Bronze", requirement: "Log water once.", count: 1, xp: 10, icon: "fa-faucet-drop", color: "from-orange-400 to-orange-600" },
  { name: "Day 1", tier: "Bronze", requirement: "Track one full day.", count: 3, xp: 10, icon: "fa-calendar-day", color: "from-orange-400 to-orange-600" },
  { name: "Balanced Plate", tier: "Bronze", requirement: "Log a good macro day.", count: 1, xp: 10, icon: "fa-scale-balanced", color: "from-orange-400 to-orange-600" },
  { name: "Rise & Grind", tier: "Bronze", requirement: "Open app before 10 AM.", count: 0, xp: 10, icon: "fa-sun", color: "from-orange-400 to-orange-600" },
  { name: "Night Owl", tier: "Bronze", requirement: "Open app after 11 PM.", count: 0, xp: 10, icon: "fa-moon", color: "from-orange-400 to-orange-600" },
  { name: "Rookie Chef", tier: "Bronze", requirement: "Scan home-cooked meal.", count: 1, xp: 10, icon: "fa-kitchen-set", color: "from-orange-400 to-orange-600" },
  { name: "First Friend", tier: "Bronze", requirement: "Add 1 friend.", count: 0, xp: 10, icon: "fa-user-plus", color: "from-orange-400 to-orange-600" },
  { name: "Share & Care", tier: "Bronze", requirement: "Share app link.", count: 0, xp: 10, icon: "fa-share-nodes", color: "from-orange-400 to-orange-600" },
  { name: "Scan Clean", tier: "Bronze", requirement: "First high-quality scan.", count: 1, xp: 10, icon: "fa-camera-retro", color: "from-orange-400 to-orange-600" },
  { name: "Rookie Logger", tier: "Bronze", requirement: "Log 3 meals in a day.", count: 3, xp: 10, icon: "fa-clipboard-list", color: "from-orange-400 to-orange-600" },

  // 🥈 SILVER (20)
  { name: "Week Warrior", tier: "Silver", requirement: "7-day usage.", count: 7, xp: 25, icon: "fa-shield", color: "from-slate-400 to-slate-600" },
  { name: "10 Scans", tier: "Silver", requirement: "Scan 10 meals total.", count: 10, xp: 25, icon: "fa-barcode", color: "from-slate-400 to-slate-600" },
  { name: "Protein Puncher", tier: "Silver", requirement: "60g protein in a day.", count: 10, xp: 25, icon: "fa-dumbbell", color: "from-slate-400 to-slate-600" },
  { name: "Carb Controller", tier: "Silver", requirement: "Low carb week (7 days).", count: 21, xp: 25, icon: "fa-gauge-simple", color: "from-slate-400 to-slate-600" },
  { name: "Fat Fighter", tier: "Silver", requirement: "Low fat day.", count: 3, xp: 25, icon: "fa-fire-extinguisher", color: "from-slate-400 to-slate-600" },
  { name: "Hydration Hero", tier: "Silver", requirement: "7 water logs total.", count: 7, xp: 25, icon: "fa-droplet", color: "from-slate-400 to-slate-600" },
  { name: "3-Day Streak", tier: "Silver", requirement: "No break for 3 days.", count: 9, xp: 25, icon: "fa-bolt", color: "from-slate-400 to-slate-600" },
  { name: "Early Bird", tier: "Silver", requirement: "8 AM login.", count: 0, xp: 25, icon: "fa-kiwi-bird", color: "from-slate-400 to-slate-600" },
  { name: "Meal Logger", tier: "Silver", requirement: "Log daily for 3 days.", count: 9, xp: 25, icon: "fa-pen-to-square", color: "from-slate-400 to-slate-600" },
  { name: "Packaged Scan", tier: "Silver", requirement: "Scan 5 packaged foods.", count: 5, xp: 25, icon: "fa-box", color: "from-slate-400 to-slate-600" },
  { name: "Fruit Fiesta", tier: "Silver", requirement: "Log 5 fruits.", count: 5, xp: 25, icon: "fa-lemon", color: "from-slate-400 to-slate-600" },
  { name: "Veggie Lover", tier: "Silver", requirement: "Log 5 vegetables.", count: 5, xp: 25, icon: "fa-broccoli", color: "from-slate-400 to-slate-600" },
  { name: "Healthy Sun", tier: "Silver", requirement: "Clean Sunday logging.", count: 1, xp: 25, icon: "fa-umbrella-beach", color: "from-slate-400 to-slate-600" },
  { name: "Low Sugar Day", tier: "Silver", requirement: "< 20g sugar logged.", count: 3, xp: 25, icon: "fa-cubes-stacked", color: "from-slate-400 to-slate-600" },
  { name: "Light Dinner", tier: "Silver", requirement: "< 500 kcal dinner.", count: 1, xp: 25, icon: "fa-bowl-rice", color: "from-slate-400 to-slate-600" },
  { name: "Anti-Junk", tier: "Silver", requirement: "24h no junk food.", count: 3, xp: 25, icon: "fa-ban-smoking", color: "from-slate-400 to-slate-600" },
  { name: "Team Player", tier: "Silver", requirement: "2 friends added.", count: 0, xp: 25, icon: "fa-people-group", color: "from-slate-400 to-slate-600" },
  { name: "First Victory", tier: "Silver", requirement: "Beat friend once.", count: 0, xp: 25, icon: "fa-flag-checkered", color: "from-slate-400 to-slate-600" },
  { name: "Streak Saver", tier: "Silver", requirement: "Used streak freeze.", count: 0, xp: 25, icon: "fa-snowflake", color: "from-slate-400 to-slate-600" },
  { name: "Bronze Master", tier: "Silver", requirement: "All bronze badges earned.", count: 20, xp: 25, icon: "fa-boxes-stacked", color: "from-slate-400 to-slate-600" },

  // 🏅 GOLD (20)
  { name: "30 Scans", tier: "Gold", requirement: "Total 30 scans.", count: 30, xp: 50, icon: "fa-qrcode", color: "from-yellow-400 to-yellow-600" },
  { name: "Weekly Streak", tier: "Gold", requirement: "7 days continuous.", count: 21, xp: 50, icon: "fa-fire", color: "from-yellow-400 to-yellow-600" },
  { name: "Macro Master", tier: "Gold", requirement: "5 perfect macro days.", count: 15, xp: 50, icon: "fa-bullseye", color: "from-yellow-400 to-yellow-600" },
  { name: "Iron Protein", tier: "Gold", requirement: "80g protein in a day.", count: 15, xp: 50, icon: "fa-weight-hanging", color: "from-yellow-400 to-yellow-600" },
  { name: "Water Machine", tier: "Gold", requirement: "Log 2L water in a day.", count: 2, xp: 50, icon: "fa-faucet", color: "from-yellow-400 to-yellow-600" },
  { name: "Nutrition Nerd", tier: "Gold", requirement: "20 different foods scanned.", count: 20, xp: 50, icon: "fa-book-open-reader", color: "from-yellow-400 to-yellow-600" },
  { name: "Chef Mode", tier: "Gold", requirement: "10 home cooked meals.", count: 10, xp: 50, icon: "fa-hat-chef", color: "from-yellow-400 to-yellow-600" },
  { name: "No Cheat 3", tier: "Gold", requirement: "3 days no cheat meals.", count: 9, xp: 50, icon: "fa-shield-halved", color: "from-yellow-400 to-yellow-600" },
  { name: "Salad King", tier: "Gold", requirement: "15 salads logged.", count: 15, xp: 50, icon: "fa-leaf", color: "from-yellow-400 to-yellow-600" },
  { name: "Calorie Capt.", tier: "Gold", requirement: "14-day logging.", count: 42, xp: 50, icon: "fa-anchor", color: "from-yellow-400 to-yellow-600" },
  { name: "5 Friends", tier: "Gold", requirement: "5 friends added.", count: 0, xp: 50, icon: "fa-users", color: "from-yellow-400 to-yellow-600" },
  { name: "Top 50", tier: "Gold", requirement: "Reach Top 50 leaderboard.", count: 0, xp: 50, icon: "fa-ranking-star", color: "from-yellow-400 to-yellow-600" },
  { name: "Premium", tier: "Gold", requirement: "Supporter status.", count: 0, xp: 50, icon: "fa-star", color: "from-yellow-400 to-yellow-600" },
  { name: "Low Carb Pro", tier: "Gold", requirement: "< 100g carb day.", count: 10, xp: 50, icon: "fa-feather", color: "from-yellow-400 to-yellow-600" },
  { name: "Fat Limit", tier: "Gold", requirement: "< 40g fat day.", count: 10, xp: 50, icon: "fa-bottle-droplet", color: "from-yellow-400 to-yellow-600" },
  { name: "Full Day Log", tier: "Gold", requirement: "Log B+L+D in a day.", count: 3, xp: 50, icon: "fa-check-double", color: "from-yellow-400 to-yellow-600" },
  { name: "Perfect Week", tier: "Gold", requirement: "7 perfect logging days.", count: 21, xp: 50, icon: "fa-calendar-check", color: "from-yellow-400 to-yellow-600" },
  { name: "Balanced Ch.", tier: "Gold", requirement: "Consistency at peak.", count: 20, xp: 50, icon: "fa-medal", color: "from-yellow-400 to-yellow-600" },
  { name: "Silver Col.", tier: "Gold", requirement: "All silver badges earned.", count: 40, xp: 50, icon: "fa-layer-group", color: "from-yellow-400 to-yellow-600" },
  { name: "Monthly Log", tier: "Gold", requirement: "30-day usage total.", count: 90, xp: 50, icon: "fa-calendar-week", color: "from-yellow-400 to-yellow-600" },

  // 💎 PLATINUM (20)
  { name: "100 Scans", tier: "Platinum", requirement: "Scan 100 food items.", count: 100, xp: 100, icon: "fa-expand", color: "from-slate-200 to-blue-400" },
  { name: "30-Day Streak", tier: "Platinum", requirement: "Monthly non-stop logging.", count: 90, xp: 100, icon: "fa-fire-flame-curved", color: "from-slate-200 to-blue-400" },
  { name: "Protein Beast", tier: "Platinum", requirement: "100g protein in a day.", count: 30, xp: 100, icon: "fa-hand-fist", color: "from-slate-200 to-blue-400" },
  { name: "Progressive", tier: "Platinum", requirement: "Log a weight change.", count: 0, xp: 100, icon: "fa-arrow-trend-up", color: "from-slate-200 to-blue-400" },
  { name: "Sugar Free Wk", tier: "Platinum", requirement: "7 days zero added sugar.", count: 21, xp: 100, icon: "fa-ghost", color: "from-slate-200 to-blue-400" },
  { name: "Clean Week", tier: "Platinum", requirement: "All logs 'Clean' for 7 days.", count: 21, xp: 100, icon: "fa-soap", color: "from-slate-200 to-blue-400" },
  { name: "Gym Rat", tier: "Platinum", requirement: "5 sessions logged.", count: 0, xp: 100, icon: "fa-dumbbell", color: "from-slate-200 to-blue-400" },
  { name: "Marathon Log", tier: "Platinum", requirement: "Log 7 items in one day.", count: 7, xp: 100, icon: "fa-person-running", color: "from-slate-200 to-blue-400" },
  { name: "Veteran", tier: "Platinum", requirement: "3 months app usage.", count: 0, xp: 100, icon: "fa-award", color: "from-slate-200 to-blue-400" },
  { name: "Explorer", tier: "Platinum", requirement: "50 unique foods scanned.", count: 50, xp: 100, icon: "fa-compass", color: "from-slate-200 to-blue-400" },
  { name: "Cook Master", tier: "Platinum", requirement: "30 home cooked meals.", count: 30, xp: 100, icon: "fa-kitchen-set", color: "from-slate-200 to-blue-400" },
  { name: "Top 10", tier: "Platinum", requirement: "Reach Top 10 leaderboard.", count: 0, xp: 100, icon: "fa-trophy", color: "from-slate-200 to-blue-400" },
  { name: "Dinner Week", tier: "Platinum", requirement: "7 healthy dinners logged.", count: 7, xp: 100, icon: "fa-shrimp", color: "from-slate-200 to-blue-400" },
  { name: "Fat Burn Wk", tier: "Platinum", requirement: "Low fat week (7 days).", count: 21, xp: 100, icon: "fa-bolt-lightning", color: "from-slate-200 to-blue-400" },
  { name: "Bulk Week", tier: "Platinum", requirement: "High protein week (7 days).", count: 21, xp: 100, icon: "fa-mountain", color: "from-slate-200 to-blue-400" },
  { name: "Gold Collector", tier: "Platinum", requirement: "All gold badges earned.", count: 60, xp: 100, icon: "fa-gem", color: "from-slate-200 to-blue-400" },
  { name: "Scientist", tier: "Platinum", requirement: "Log 5 custom items.", count: 5, xp: 100, icon: "fa-flask", color: "from-slate-200 to-blue-400" },
  { name: "Quiz Master", tier: "Platinum", requirement: "90% score in nutrition quiz.", count: 0, xp: 100, icon: "fa-graduation-cap", color: "from-slate-200 to-blue-400" },
  { name: "Challenger", tier: "Platinum", requirement: "3 community challenges won.", count: 0, xp: 100, icon: "fa-swords", color: "from-slate-200 to-blue-400" },
  { name: "Budget King", tier: "Platinum", requirement: "Hit monthly cal target exactly.", count: 0, xp: 100, icon: "fa-piggy-bank", color: "from-slate-200 to-blue-400" },

  // 🔷 DIAMOND (20)
  { name: "365 Logs", tier: "Diamond", requirement: "Total 365 meal logs.", count: 365, xp: 250, icon: "fa-infinity", color: "from-cyan-400 to-blue-600" },
  { name: "200 Scans", tier: "Diamond", requirement: "Scan 200 food items.", count: 200, xp: 250, icon: "fa-camera-rotate", color: "from-cyan-400 to-blue-600" },
  { name: "90-Day Streak", tier: "Diamond", requirement: "3 month streak.", count: 270, xp: 250, icon: "fa-fire-flame-simple", color: "from-cyan-400 to-blue-600" },
  { name: "Achiever", tier: "Diamond", requirement: "Reach target weight goal.", count: 0, xp: 250, icon: "fa-flag", color: "from-cyan-400 to-blue-600" },
  { name: "Perfect 14", tier: "Diamond", requirement: "14-day perfect macro streak.", count: 42, xp: 250, icon: "fa-star-half-stroke", color: "from-cyan-400 to-blue-600" },
  { name: "Clean Month", tier: "Diamond", requirement: "30-day no junk food.", count: 90, xp: 250, icon: "fa-leaf", color: "from-cyan-400 to-blue-600" },
  { name: "Elite Athlete", tier: "Diamond", requirement: "60 workouts logged.", count: 0, xp: 250, icon: "fa-person-swimming", color: "from-cyan-400 to-blue-600" },
  { name: "Water Lord", tier: "Diamond", requirement: "3L water / 10 days straight.", count: 30, xp: 250, icon: "fa-ocean", color: "from-cyan-400 to-blue-600" },
  { name: "Rank #1", tier: "Diamond", requirement: "Global #1 Leaderboard.", count: 0, xp: 250, icon: "fa-crown", color: "from-cyan-400 to-blue-600" },
  { name: "Loyal User", tier: "Diamond", requirement: "1-year premium status.", count: 0, xp: 250, icon: "fa-user-shield", color: "from-cyan-400 to-blue-600" },
  { name: "Calippo Chef", tier: "Diamond", requirement: "30 custom meal creations.", count: 30, xp: 250, icon: "fa-utensils", color: "from-cyan-400 to-blue-600" },
  { name: "Quiz Streak", tier: "Diamond", requirement: "50 correct quiz answers.", count: 0, xp: 250, icon: "fa-bolt", color: "from-cyan-400 to-blue-600" },
  { name: "100 Home", tier: "Diamond", requirement: "100 home cooked meals.", count: 100, xp: 250, icon: "fa-house-chimney", color: "from-cyan-400 to-blue-600" },
  { name: "Beat 10", tier: "Diamond", requirement: "Beat 10 friends total.", count: 0, xp: 250, icon: "fa-people-arrows", color: "from-cyan-400 to-blue-600" },
  { name: "Ultra Keto", tier: "Diamond", requirement: "Ultra low carb week.", count: 21, xp: 250, icon: "fa-snowflake", color: "from-cyan-400 to-blue-600" },
  { name: "Hulk Protein", tier: "Diamond", requirement: "150g protein in a day.", count: 50, xp: 250, icon: "fa-hand-fist", color: "from-cyan-400 to-blue-600" },
  { name: "Plat Col.", tier: "Diamond", requirement: "All platinum badges earned.", count: 80, xp: 250, icon: "fa-gem", color: "from-cyan-400 to-blue-600" },
  { name: "Half Year", tier: "Diamond", requirement: "180-day streak.", count: 540, xp: 250, icon: "fa-infinity", color: "from-cyan-400 to-blue-600" },
  { name: "Unbreakable", tier: "Diamond", requirement: "No miss logged month.", count: 90, xp: 250, icon: "fa-lock", color: "from-cyan-400 to-blue-600" },
  { name: "New Me", tier: "Diamond", requirement: "Significant transformation.", count: 0, xp: 250, icon: "fa-user-gear", color: "from-cyan-400 to-blue-600" },

  // 🔱 MYTHIC (20)
  { name: "Immortal", tier: "Mythic", requirement: "365-day logging streak.", count: 365, xp: 500, icon: "fa-bolt-lightning", color: "from-purple-600 to-black", animation: "animate-pulse" },
  { name: "Calippo God", tier: "Mythic", requirement: "1000 total scans.", count: 1000, xp: 500, icon: "fa-dragon", color: "from-purple-600 to-black", animation: "animate-bounce" },
  { name: "Macro Perfect", tier: "Mythic", requirement: "30 macro perfect days.", count: 90, xp: 500, icon: "fa-eye", color: "from-purple-600 to-black" },
  { name: "Zero Junk 100", tier: "Mythic", requirement: "100 days junk-free.", count: 300, xp: 500, icon: "fa-skull-crossbones", color: "from-purple-600 to-black" },
  { name: "Dia Col.", tier: "Mythic", requirement: "All diamond badges earned.", count: 100, xp: 500, icon: "fa-gem", color: "from-purple-600 to-black" },
  { name: "Legendary", tier: "Mythic", requirement: "250 workouts logged.", count: 0, xp: 500, icon: "fa-mountain-sun", color: "from-purple-600 to-black" },
  { name: "Ch. Elite", tier: "Mythic", requirement: "20 challenges won.", count: 0, xp: 500, icon: "fa-shield-cat", color: "from-purple-600 to-black" },
  { name: "60 Perfect", tier: "Mythic", requirement: "60-day perfect intake.", count: 180, xp: 500, icon: "fa-star", color: "from-purple-600 to-black" },
  { name: "Rock Solid", tier: "Mythic", requirement: "BMI stable 6 months.", count: 0, xp: 500, icon: "fa-cube", color: "from-purple-600 to-black" },
  { name: "Verified", tier: "Mythic", requirement: "Verified transformation.", count: 0, xp: 500, icon: "fa-circle-check", color: "from-purple-600 to-black" },
  { name: "Evangelist", tier: "Mythic", requirement: "Refer 20 users.", count: 0, xp: 500, icon: "fa-bullhorn", color: "from-purple-600 to-black" },
  { name: "Master Chef", tier: "Mythic", requirement: "200 cooked meals.", count: 200, xp: 500, icon: "fa-kitchen-set", color: "from-purple-600 to-black" },
  { name: "Monk Life", tier: "Mythic", requirement: "Wake 5 AM for 60 days.", count: 0, xp: 500, icon: "fa-sun", color: "from-purple-600 to-black" },
  { name: "Eternal Log", tier: "Mythic", requirement: "365 days no miss.", count: 1095, xp: 500, icon: "fa-scroll", color: "from-purple-600 to-black" },
  { name: "Quiz Legend", tier: "Mythic", requirement: "100 quiz streak.", count: 0, xp: 500, icon: "fa-fire-alt", color: "from-purple-600 to-black" },
  { name: "Icon", tier: "Mythic", requirement: "Featured community user.", count: 0, xp: 500, icon: "fa-id-card", color: "from-purple-600 to-black" },
  { name: "Early Bird", tier: "Mythic", requirement: "Early supporter badge.", count: 0, xp: 500, icon: "fa-feather", color: "from-purple-600 to-black" },
  { name: "Mythic Col.", tier: "Mythic", requirement: "All Mythic tiers unlocked.", count: 120, xp: 500, icon: "fa-hand-sparkles", color: "from-purple-600 to-black" },
  { name: "God Mode", tier: "Mythic", requirement: "All 120 badges earned.", count: 10000, xp: 500, icon: "fa-crown", color: "from-purple-600 to-black" },
  { name: "The Immortal", tier: "Mythic", requirement: "2 years of usage.", count: 0, xp: 500, icon: "fa-ghost", color: "from-purple-600 to-black" },
];

export const TIER_CONFIG = {
  Bronze: { bg: 'bg-orange-100 text-orange-700', label: '🥉 Bronze', shadow: 'shadow-orange-200' },
  Silver: { bg: 'bg-slate-100 text-slate-700', label: '🥈 Silver', shadow: 'shadow-slate-200' },
  Gold: { bg: 'bg-yellow-100 text-yellow-700', label: '🏅 Gold', shadow: 'shadow-yellow-200' },
  Platinum: { bg: 'bg-blue-50 text-blue-700', label: '💎 Platinum', shadow: 'shadow-blue-100' },
  Diamond: { bg: 'bg-cyan-50 text-cyan-700', label: '🔷 Diamond', shadow: 'shadow-cyan-100' },
  Mythic: { bg: 'bg-purple-100 text-purple-700', label: '🔱 Mythic', shadow: 'shadow-purple-200' }
};
